import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

//sf-pro is not available on my mac device that why i use nearly matches INter font
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sf-pro",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
